use nlplug-findfs for decryption
this makes it possible to use UUID-based naming-schemes

diff --git a/initramfs-init-dropbear b/initramfs-init-dropbear
--- a/initramfs-init-dropbear
+++ b/initramfs-init-dropbear
@@ -373,9 +373,7 @@ eend 0
 if [ -n "$KOPT_dropbear" ]; then
 	configure_ip
 	if [ -n "$KOPT_cryptroot" ]; then
-	  # wait for blk device to appear
-	  nlplug-findfs -p /sbin/mdev ${KOPT_debug_init:+-d} ${KOPT_cryptroot}
-	  setup_dropbear || echo "Failed to uncrypt root via ssh"
+		setup_dropbear || echo "Failed to uncrypt root via ssh"
 	fi
 elif [ -n "$KOPT_cryptroot" ]; then
 	cryptopts="-c ${KOPT_cryptroot}"
